import { Box, Typography } from "@mui/material";
import { red } from "@mui/material/colors";
import type { NextPage } from "next";
import Head from "next/head";
import { css } from "@emotion/react";

const root = css`
  display: flex;
  justify-content: center;
  align-items: center;
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box css={root}>
        <Typography variant="h1" color={red[100]} mr="1rem">
          Welcome
        </Typography>
        <Typography variant="h1">to sports!</Typography>
      </Box>
    </>
  );
};

export default Home;
